### ISSUE TITLE
[Vote Plug-in] Error message about the record number may be misleading

### ISSUE THREAD

**Issue by yamaryu0508** [kintone/plugin-examples#105]
レコード番号フィールドを表示しているレコード一覧画面でも「レコード番号フィールドが見つかりません。いいねプラグインを使うためには、フォーム編集画面でレコード番号フィールドを配置する必要があります。」が表示されているようです。一覧画面における動作条件はメッセージの表示通りの条件だけでしょうか？

少し調べさせて頂くと、/k/v1/formのAPIのレスポンスからRECORD_NUMBERが消えた？ように思われます。ドキュメントによればRECORD_NUMBERは対応中のようですが、他のビルトインフィールドも同様でしたので、原因としてはこの辺かなぁと思いました（ドメイン等を変えたりして試しましたが同様でした）。

**Comment by yamaryu0508** [comment]
レコード番号フィールドを表示しているレコード一覧画面でも「レコード番号フィールドが見つかりません。いいねプラグインを使うためには、フォーム編集画面でレコード番号フィールドを配置する必要があります。」が表示されているようです。

少し調べさせて頂くと、`/k/v1/form`のAPIのレスポンスから`RECORD_NUMBER`が消えた？ように思われます。[ドキュメント](https://developer.cybozu.io/hc/ja/articles/201941834)によれば`RECORD_NUMBER`は対応中のようですが、他のビルトインフィールドも同様でしたので、原因としてはこの辺かなぁと思いました（ドメイン等を変えたりして試しましたが同様でした）。

**Comment by will-yama** [comment]
Translation and summary of the above - not placing the record number in the record list view caused an error to state that the record number field needed to be included in the form. This in fact should have been stating that the record number field should be included in the view field.

This has been fixed with #123 
We actually shouldn't have been using the /form/layout API to identify if a record number field existed in the List view, because...well we can't identify it.
